### ISSUE TITLE
Nothing is shown wnen project is opened

### ISSUE THREAD

**Issue by wanbinkimoon** [keijiro/DxrLattice#1]
10/ out of 10 i'm missing something but when the project is opened all I can see is a blank canvas

**Comment by keijiro** [comment]
Which GPU and driver version are you using?

**Comment by wanbinkimoon** [comment]
I'm on a 2020 macbookpro 16"

**Comment by keijiro** [comment]
As noted on README, this is an example project for DXR (DirectX Raytracing). You need a Windows PC with a DXR-compatible graphics card (like GeForce RTX).

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further problems.

**Comment by wanbinkimoon** [comment]
thanks for the info, sorryy I missed the readme :)
